service: auth-functions

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

package:
  excludeDevDependencies: true
  patterns:
    - '!**/**' # ignores all files
    - dist/** # includes only files from dist dir

functions:
  signIn:
    handler: dist/shared/infra/index.signInHandler
     events:
      - http:
          path: sign-in
          method: post
