service: auth-functions

frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - "!!(dist/**)"
    - dist/**

layers:
  node-shared:
    path: dist
    name: node-shared-${sls:stage}
    description: Shared layer
    compatibleRuntimes:
      - nodejs16.x
    package:
      patterns:
        - "!!(src/shared/**)"
        - "node_modules/**"
        - "src/shared/**"
        - "!yarn.lock"
        - "!package-lock.json"

functions:
  signIn:
    handler: dist/src/sign-in/infra/SignInLambdaHandler.handler
    layers:
      - !Ref NodeSharedLambdaLayer
    package:
      patterns:
        - "!!(dist/src/sign-in/**)"

    events:
      - http: POST /sign-in

  helloWorld:
    handler: dist/src/hello-world/infra/HelloWorldLambdaHandler.handler
    package:
      patterns:
        - "!!(dist/src/hello-world/**)"

    events:
      - http: GET /hello
