service: auth-functions

frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x

package:
  excludeDevDependencies: false
  individually: true
  patterns:
    - "!!(dist/**)"
    - dist/**

layers:
  shared:
    path: .
    name: shared-${sls:stage}
    description: Shared layer
    compatibleRuntimes:
      - nodejs16.x
    package:
      patterns:
        - "!!(dist/**/(shared|node_modules)/**)"
        - "!dist/yarn.lock"
        - "!dist/package-lock.json"

functions:
  signIn:
    handler: dist/src/sign-in/infra/SignInLambdaHandler.handler
    layers:
      - !Ref SharedLambdaLayer
    package:
      patterns:
        - "!!(dist/src/sign-in/**)"

    events:
      - http: POST /sign-in

  helloWorld:
    handler: dist/src/hello-world/infra/HelloWorldLambdaHandler.handler
    package:
      patterns:
        - "!!(dist/src/hello-world/**)"

    events:
      - http: GET /hello
