service: auth-functions

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

package:
  excludeDevDependencies: true
  patterns:
    - "!**/**" # ignores all files
    - dist/** # includes only files from dist dir
    - package.json

functions:
  signIn:
    handler: dist/src/shared/infra/index.signInHandler
    events:
      - http:
          path: sign-in
          method: post

  helloWorld:
    handler: dist/src/shared/infra/index.helloWorld
    events:
      - http:
          path: hello
          method: get
